version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo the build started on `date`
      - echo building the docker image
      - docker build -t nodeapp:1 .
      - docker tag nodeapp:1 728738226157.dkr.ecr.us-east-1.amazonaws.com/nodeapp
  post_build:
    commands: 
      - echo build completed on `date`
      - echo pushing the docker image
      - docker push 728738226157.dkr.ecr.us-east-1.amazonaws.com/nodeapp
